name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Chechout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-pyhton@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r app/src/requirements.txt

      - name: Run tests
        run: python -m unittest discover -s app/tests

      - name: Build Docker image
        run: docker build -t myflaskapp:latest app
